/**
 * 服务状态（INFO / stats）字段说明字典
 * 为“服务状态”页的每个指标提供作用说明
 */

/** Redis INFO 字段说明 */
const REDIS_DESC: Record<string, string> = {
  // ===== server =====
  redis_version: "Redis 服务器版本号",
  redis_git_sha1: "Git 提交哈希（源码对应版本）",
  redis_git_dirty: "源码是否有未提交的修改（0=干净，1=有改动）",
  redis_build_id: "构建 ID（每次编译生成）",
  redis_mode: "运行模式：standalone（单机）/ cluster（集群）/ sentinel（哨兵）",
  os: "服务器操作系统",
  arch_bits: "架构位数（32 或 64）",
  multiplexing_api: "事件循环多路复用实现（epoll/kqueue 等）",
  process_id: "Redis 进程 PID",
  run_id: "本次启动的随机运行标识（每次重启都会变化）",
  tcp_port: "TCP 监听端口",
  server_time_usec: "服务器当前时间（微秒）",
  uptime_in_seconds: "服务器已连续运行的秒数",
  uptime_in_days: "服务器已连续运行的天数",
  hz: "内部事件循环调度频率（每秒次数）",
  configured_hz: "配置文件中设置的调度频率",
  lru_clock: "LRU 时钟（用于键淘汰与过期计算）",
  executable: "Redis 可执行文件的完整路径",
  config_file: "Redis 配置文件的路径（无则显示空）",
  io_threads_active: "当前活跃的 IO 线程数",
  // ===== clients =====
  connected_clients: "当前已连接的客户端数量",
  cluster_connections: "集群模式下与其他节点的连接数",
  maxclients: "最大允许的客户端连接数（配置上限）",
  client_recent_max_input_buffer: "最近观测到的最大客户端输入缓冲区（字节）",
  client_recent_max_output_buffer: "最近观测到的最大客户端输出缓冲区（字节）",
  blocked_clients: "正在等待阻塞命令（BLPOP 等）的客户端数",
  tracking_clients: "开启客户端缓存追踪的客户端数",
  clients_in_timeout_table: "记录在超时表中的客户端数",
  total_watched_keys: "当前被 WATCH 监视的键总数",
  // ===== memory =====
  used_memory: "Redis 分配器已使用的内存（字节）",
  used_memory_human: "已使用内存（人类可读格式，如 1.2M）",
  used_memory_rss: "操作系统视角的常驻内存 RSS（字节）",
  used_memory_rss_human: "常驻内存 RSS（人类可读格式）",
  used_memory_peak: "历史内存使用峰值（字节）",
  used_memory_peak_human: "历史内存使用峰值（人类可读）",
  used_memory_lua: "Lua 脚本引擎占用的内存（字节）",
  used_memory_scripts: "脚本缓存（EVAL 脚本）占用的内存",
  used_memory_overhead: "除数据外的基础开销（缓冲、键结构等）",
  used_memory_startup: "服务器启动时占用的固定内存",
  used_memory_dataset: "数据集（实际键值数据）占用的内存",
  used_memory_dataset_perc: "数据集内存占已用内存的比例",
  total_system_memory: "服务器物理内存总量（字节）",
  total_system_memory_human: "服务器物理内存总量（人类可读）",
  maxmemory: "内存使用上限（0 表示不限制）",
  maxmemory_policy: "达到内存上限时的淘汰策略（noeviction/allkeys-lru 等）",
  mem_fragmentation_ratio: "内存碎片率（RSS/分配内存，过高需关注碎片）",
  mem_fragmentation_bytes: "内存碎片差值（字节）",
  mem_allocator: "内存分配器（jemalloc/libc 等）",
  allocator_active: "分配器活跃内存（字节）",
  allocator_allocated: "分配器已分配内存（字节）",
  allocator_resident: "分配器驻留内存（字节）",
  // ===== persistence =====
  loading: "是否正在加载持久化数据（0=否，1=是）",
  rdb_changes_since_last_save: "自上次成功保存以来发生变更的次数",
  rdb_bgsave_in_progress: "是否正在进行后台 RDB 保存（0/1）",
  rdb_last_save_time: "上次成功保存 RDB 的 Unix 时间戳",
  rdb_last_bgsave_status: "上次后台保存的结果状态（ok/err）",
  rdb_last_bgsave_time_sec: "上次后台保存耗时（秒）",
  rdb_current_bgsave_time_sec: "当前正在进行的后台保存已耗时（秒，-1 表示无）",
  aof_enabled: "是否启用 AOF 持久化（0/1）",
  aof_rewrite_in_progress: "是否正在进行 AOF 重写（0/1）",
  aof_rewrite_scheduled: "是否有 AOF 重写已排期等待执行",
  aof_last_write_status: "上次 AOF 写入结果状态（ok/err）",
  aof_last_bgrewrite_status: "上次 AOF 后台重写结果状态",
  aof_current_size: "AOF 文件当前大小（字节）",
  aof_base_size: "AOF 重写后的基准文件大小（字节）",
  aof_current_rewrite_time_sec: "当前 AOF 重写已耗时（秒，-1 表示无）",
  // ===== stats =====
  total_connections_received: "累计接收的客户端连接总数",
  total_commands_processed: "累计处理的命令总数",
  instantaneous_ops_per_sec: "当前瞬时每秒处理的命令数（QPS）",
  total_net_input_bytes: "累计网络输入字节数",
  total_net_output_bytes: "累计网络输出字节数",
  rejected_connections: "因超出 maxclients 而被拒绝的连接数",
  sync_full: "从节点完成的完整（全量）同步次数",
  sync_partial_ok: "从节点完成的部分同步成功次数",
  sync_partial_err: "部分同步失败而回退全量同步的次数",
  expired_keys: "累计被淘汰的过期键数量",
  evicted_keys: "因内存上限被主动驱逐的键数量",
  keyspace_hits: "键查找命中次数（越高越好）",
  keyspace_misses: "键查找未命中次数（过高可能缓存命中率低）",
  pubsub_channels: "当前活跃的发布订阅频道数",
  pubsub_patterns: "当前活跃的发布订阅模式数",
  latest_fork_usec: "最近一次 fork（持久化）耗时（微秒）",
  total_forks: "服务器累计 fork 次数",
  // ===== replication =====
  role: "当前角色：master（主）/ slave（从）",
  connected_slaves: "已连接的从节点数量",
  master_replid: "主节点复制 ID（用于增量同步）",
  master_repl_offset: "主节点当前的复制偏移量",
  second_repl_offset: "第二个复制偏移量（用于故障切换后增量同步）",
  repl_backlog_active: "复制积压缓冲区是否启用",
  repl_backlog_size: "复制积压缓冲区大小（字节）",
  repl_backlog_first_byte_offset: "复制积压缓冲区中最早的字节偏移",
  repl_backlog_histlen: "复制积压缓冲区中已使用的字节数",
  master_host: "主节点主机地址（从节点视角）",
  master_port: "主节点端口（从节点视角）",
  master_link_status: "主从链接状态（up/down）",
  master_last_io_seconds_ago: "距上次与主节点通信的秒数",
  master_sync_in_progress: "是否正在进行主从全量同步",
  slave_repl_offset: "从节点当前的复制偏移量",
  slave_priority: "从节点的优先级（用于哨兵选举）",
  slave_read_only: "从节点是否只读（1=只读）",
  // ===== cpu =====
  used_cpu_sys: "Redis 主进程消耗的系统 CPU 时间（秒）",
  used_cpu_user: "Redis 主进程消耗的用户 CPU 时间（秒）",
  used_cpu_sys_children: "子进程（持久化）消耗的系统 CPU 时间（秒）",
  used_cpu_user_children: "子进程（持久化）消耗的用户 CPU 时间（秒）",
  // ===== cluster =====
  cluster_enabled: "是否启用集群模式（0/1）",
  // ===== keyspace =====
  keyspace: "各数据库的键数量与过期信息（keys=总数, expires=过期键数, avg_ttl=平均 TTL）",
};

/** Memcached stats 字段说明 */
const MEMCACHED_DESC: Record<string, string> = {
  pid: "Memcached 进程 PID",
  uptime: "服务器已运行时长（秒）",
  time: "服务器当前时间戳",
  version: "Memcached 版本号",
  pointer_size: "指针位数（64=64 位系统）",
  rusage_user: "进程累计用户 CPU 时间",
  rusage_system: "进程累计系统 CPU 时间",
  max_connections: "最大允许连接数（配置上限）",
  curr_connections: "当前打开的连接数",
  total_connections: "累计建立的连接总数",
  rejected_connections: "因达到上限而被拒绝的连接数",
  connection_structures: "为连接分配的结构数量",
  response_obj_oom: "响应对象因内存不足而失败的次数",
  response_obj_count: "当前响应对象数量",
  response_obj_bytes: "响应对象占用字节数",
  read_buf_count: "读缓冲区数量",
  read_buf_bytes: "读缓冲区占用字节",
  read_buf_bytes_free: "读缓冲区空闲字节",
  reserved_fds: "为内部保留的文件描述符数",
  cmd_get: "GET 请求总次数",
  cmd_set: "SET 请求总次数",
  cmd_flush: "FLUSH_ALL 请求次数",
  cmd_touch: "TOUCH 请求次数",
  cmd_meta: "元数据命令请求次数",
  get_hits: "GET 命中次数（key 存在）",
  get_misses: "GET 未命中次数（key 不存在）",
  get_expired: "GET 命中但数据已过期的次数",
  get_flushed: "数据被 flush 清除后读取的次数",
  delete_misses: "DELETE 未命中次数（key 不存在）",
  delete_hits: "DELETE 命中次数",
  incr_misses: "INCR 未命中次数",
  incr_hits: "INCR 命中次数",
  decr_misses: "DECR 未命中次数",
  decr_hits: "DECR 命中次数",
  cas_misses: "CAS 未命中次数（key 不存在）",
  cas_hits: "CAS 命中并更新成功的次数",
  cas_badval: "CAS 因值被修改而失败的次数",
  touch_hits: "TOUCH 命中次数",
  touch_misses: "TOUCH 未命中次数",
  auth_cmds: "SASL 认证命令次数",
  auth_errors: "SASL 认证失败次数",
  bytes_read: "累计从网络读取的字节数",
  bytes_written: "累计写入网络的字节数",
  limit_maxbytes: "内存使用上限（字节）",
  accepting_conns: "是否接受新连接（1=接受）",
  listen_disabled_num: "因达到上限而暂停监听的次数",
  time_in_listen_disabled_us: "暂停监听的总时长（微秒）",
  threads: "工作线程数量",
  conn_yields: "连接让出 CPU 的次数",
  hash_power_level: "哈希表容量级别（2 的幂）",
  hash_bytes: "哈希表占用内存（字节）",
  hash_is_expanding: "哈希表是否正在扩容（0/1）",
  slab_reassign_running: "是否正在进行 slab 重新分配",
  slabs_moved: "已移动的 slab 页数",
  tch_moved: "移动的临时 chunk 数",
  expired_unfetched: "未读取就被过期清理的条目数",
  evicted_unfetched: "未读取就被淘汰的条目数",
  evicted_active: "活跃条目被强制淘汰的次数",
  evictions: "因内存不足被淘汰的条目总数",
  reclaimed: "被新数据重用的已淘汰条目内存次数",
  crawler_reclaimed: "LRU crawler 回收的过期条目数",
  crawler_items_checked: "LRU crawler 检查的条目数",
  lrutail_reflocked: "LRU 尾部被引用锁定无法淘汰的次数",
  moves_to_cold: "条目迁移到冷区次数",
  moves_to_warm: "条目迁移到温区次数",
  moves_within_lru: "LRU 内部迁移次数",
  direct_reclaims: "直接淘汰次数",
  lru_bumps_dropped: "LRU 提升被丢弃次数",
  total_items: "累计存储的条目总数",
  expired_reclaimed: "被回收的过期条目数",
  lru_crawler_started: "LRU crawler 是否正在运行（0/1）",
  lru_maintainer_thread: "LRU 维护线程运行状态",
  malloc_fails: "内存分配失败的次数",
  bytes: "当前存储数据占用的字节数",
  curr_items: "当前存储的条目总数",
  store_no_memory: "因内存不足而存储失败的次数",
  store_too_large: "因数据过大而存储失败的次数",
  mem_used_total: "Memcached 总内存使用（字节）",
};

/** 根据连接模式返回字段说明 */
export function infoFieldDesc(mode: string | undefined, key: string): string {
  if (mode !== "memcached" && /^db\d+$/.test(key)) {
    // keyspace 节：db0/db1... 字段共用同一条说明
    return REDIS_DESC.keyspace ?? "";
  }
  const dict = mode === "memcached" ? MEMCACHED_DESC : REDIS_DESC;
  return dict[key] ?? "";
}
